version: "3.9"

services:
  api:
    build:
      context: "SB.WebAPI"
      network_mod: host
    container_name: "supportbuddy-api-container"
    ports:
      - "8091:80"
      - "3306:3306"
    extra_hosts:
      - "dbhostaddress:94.231.103.43"