version: "3.9"

services:
  api:
    build:
      context: "SB.WebAPI"
    container_name: "supportbuddy-api-container-stage"
    ports:
      - "8980:80"
    depends_on:
      - db
    
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "supportbuddy-db-container"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=supportBuddyDatabase123!
    ports:
      - "8989:1433"
    volumes:
      - supportBuddyData:/var/opt/mssql:rw
  docker-registry:
    image: "registry"
    volumes:
      - "registry_data:/var/lib/registry"
    ports:
      - "7002:5000"
  docker-registry-ui:
    image: "parabuzzle/craneoperator"
    ports:
      - "7003:80"
    environment:
      - REGISTRY_HOST=docker-registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - SSL_VERIFY=false
      - USERNAME=admin
      - PASSWORD=vpseliten123
    depends_on:
      - docker-registry

volumes:
    supportBuddyData:
    portainer_data:
    registry_data: