version: "3.9"

services:
  api:
    build:
      context: "SB.WebAPI"
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Server=${DB_CONT_NAME};Database=sbdb_staging;User=sa;Password=supportBuddyDatabase123!;MultipleActiveResultSets=True;
    
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "${DB_CONT_NAME}"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=supportBuddyDatabase123!
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - supportBuddyData:/var/opt/mssql:rw
  docker-registry:
    image: "registry"
    volumes:
      - "registry_data:/var/lib/registry"
    ports:
      - "7002:5000"
  docker-registry-ui:
    image: "parabuzzle/craneoperator"
    ports:
      - "7003:80"
    environment:
      - REGISTRY_HOST=docker-registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - SSL_VERIFY=false
      - USERNAME=admin
      - PASSWORD=vpseliten123
    depends_on:
      - docker-registry

volumes:
    supportBuddyData:
    portainer_data:
    registry_data: